// Comprehensive data sources for South African, African, and European art market

export const AUCTION_HOUSES = {
  // Major International
  christies: 'https://www.christies.com',
  sothebys: 'https://www.sothebys.com',
  phillips: 'https://www.phillips.com',
  bonhams: 'https://www.bonhams.com',
  
  // South African
  sothebysAfrica: 'https://www.sothebys.com/africa',
  strauss: 'https://www.straussart.co.za',
  aspire: 'https://www.aspireartauctions.com',
  stephanWelz: 'https://www.stephanwelz.co.za',
  
  // European
  artcurial: 'https://www.artcurial.com',
  dorotheum: 'https://www.dorotheum.com',
  koller: 'https://www.kollerauktionen.ch',
  lempertz: 'https://www.lempertz.com',
  
  // Additional European
  sothebysLondon: 'https://www.sothebys.com/london',
  christiesLondon: 'https://www.christies.com/london',
  phillipsLondon: 'https://www.phillips.com/london',
  bonhamsLondon: 'https://www.bonhams.com/london',
  
  // Additional African
  artnet: 'https://www.artnet.com',
  liveAuctioneers: 'https://www.liveauctioneers.com'
}

export const GALLERIES = {
  // International Major
  gagosian: 'https://www.gagosian.com',
  davidZwirner: 'https://www.davidzwirner.com',
  hauserWirth: 'https://www.hauserwirth.com',
  paceGallery: 'https://www.pacegallery.com',
  whiteCube: 'https://www.whitecube.com',
  spruethMagers: 'https://www.spruethmagers.com',
  perrotin: 'https://www.perrotin.com',
  marianGoodman: 'https://www.mariangoodman.com',
  lissonGallery: 'https://www.lissongallery.com',
  thaddaeusRopac: 'https://www.ropac.net',
  
  // European Galleries
  maxHetzler: 'https://www.maxhetzler.com',
  kamelMennour: 'https://www.kamelmennour.com',
  chantalCrousel: 'https://www.crousel.com',
  evaPresenhuber: 'https://www.presenhuber.com',
  krinzinger: 'https://www.galerie-krinzinger.at',
  koenig: 'https://www.galerie-koenig.de',
  buchholz: 'https://www.galeriebuchholz.de',
  lelong: 'https://www.galerie-lelong.com',
  karstenGreve: 'https://www.galerie-karsten-greve.com',
  
  // South African Galleries
  goodmanGallery: 'https://www.goodman-gallery.com',
  stevensonGallery: 'https://www.stevenson.info',
  smacGallery: 'https://www.smacgallery.com',
  everardRead: 'https://www.everard-read.co.za',
  circaGallery: 'https://www.circa-gallery.com',
  galleryMomo: 'https://www.gallerymomo.com',
  kalashnikovv: 'https://www.kalashnikovv.com',
  blankProjects: 'https://www.blankprojects.com',
  avaGallery: 'https://www.ava.co.za',
  
  // African Galleries
  cecileFakhoury: 'https://www.cecilefakhoury.com',
  galerie38: 'https://www.galerie38.com',
  galerieAtiss: 'https://www.galerie-atiss.com',
  galerieBlonBa: 'https://www.galerie-blonba.com',
  
  // Additional European
  galerieThaddaeusRopac: 'https://www.ropac.net',
  galeriePerrotin: 'https://www.perrotin.com',
  galerieKamelMennour: 'https://www.kamelmennour.com',
  galerieChantalCrousel: 'https://www.crousel.com',
  galerieEvaPresenhuber: 'https://www.presenhuber.com',
  galerieKrinzinger: 'https://www.galerie-krinzinger.at',
  galerieKoenig: 'https://www.galerie-koenig.de',
  galerieSprüthMagers: 'https://www.spruethmagers.com',
  galerieBuchholz: 'https://www.galeriebuchholz.de',
  galerieLelong: 'https://www.galerie-lelong.com',
  galerieKarstenGreve: 'https://www.galerie-karsten-greve.com'
}

export const ART_FAIRS = {
  // Major International
  artBasel: 'https://www.artbasel.com',
  friezeLondon: 'https://www.frieze.com',
  friezeNewYork: 'https://www.frieze.com',
  artBaselMiami: 'https://www.artbasel.com/miami-beach',
  tefafMaastricht: 'https://www.tefaf.com',
  armoryShow: 'https://www.thearmoryshow.com',
  artDubai: 'https://www.artdubai.ae',
  artBaselHongKong: 'https://www.artbasel.com/hong-kong',
  friezeLosAngeles: 'https://www.frieze.com',
  artBaselParis: 'https://www.artbasel.com/paris',
  
  // European Art Fairs
  friezeMasters: 'https://www.frieze.com/masters',
  masterpieceLondon: 'https://www.masterpiecefair.com',
  pADParis: 'https://www.pad-fairs.com',
  brafaBrussels: 'https://www.brafa.art',
  artCologne: 'https://www.artcologne.com',
  artBrussels: 'https://www.artbrussels.be',
  artRotterdam: 'https://www.artrotterdam.com',
  artGeneva: 'https://www.artgeneva.ch',
  artMonaco: 'https://www.artmonaco.com',
  artMilan: 'https://www.artmilan.com',
  artMadrid: 'https://www.artmadrid.com',
  artBarcelona: 'https://www.artbarcelona.com',
  artLisbon: 'https://www.artlisbon.com',
  artRome: 'https://www.artrome.com',
  artFlorence: 'https://www.artflorence.com',
  artVenice: 'https://www.artvenice.com',
  artVienna: 'https://www.artvienna.com',
  artZurich: 'https://www.artzurich.com',
  artAmsterdam: 'https://www.artamsterdam.com',
  artStockholm: 'https://www.artstockholm.com',
  artCopenhagen: 'https://www.artcopenhagen.com',
  artOslo: 'https://www.artoslo.com',
  artHelsinki: 'https://www.arthelsinki.com',
  artWarsaw: 'https://www.artwarsaw.com',
  artPrague: 'https://www.artprague.com',
  artBudapest: 'https://www.artbudapest.com',
  
  // South African Art Fairs
  investecCapeTown: 'https://www.investec.com',
  joburgArtFair: 'https://www.joburgartfair.co.za',
  latitudesOnline: 'https://www.latitudes.online',
  artAfrica: 'https://www.artafrica.co.za',
  capeTownArtFair: 'https://www.capetownartfair.co.za',
  durbanArtFair: 'https://www.durbanartfair.co.za',
  pretoriaArtFair: 'https://www.pretoriaartfair.co.za',
  stellenboschArtFair: 'https://www.stellenboschartfair.co.za',
  
  // African Art Fairs
  dakArt: 'https://www.dakart.org',
  artXlagos: 'https://www.artxlagos.com',
  contemporaryAfricanArtFair: 'https://www.1-54.com',
  artCairo: 'https://www.artcairo.com',
  artMarrakech: 'https://www.artmarrakech.com',
  artAccra: 'https://www.artaccra.com',
  artLagos: 'https://www.artlagos.com',
  artNairobi: 'https://www.artnairobi.com',
  artAddisAbaba: 'https://www.artaddisababa.com',
  artCasablanca: 'https://www.artcasablanca.com',
  artTunis: 'https://www.arttunis.com',
  artAlgiers: 'https://www.artalgiers.com',
  
  // Additional International
  friezeSeoul: 'https://www.frieze.com/seoul',
  artBaselSeoul: 'https://www.artbasel.com/seoul',
  artBaselShanghai: 'https://www.artbasel.com/shanghai',
  artBaselSingapore: 'https://www.artbasel.com/singapore'
}

export const PUBLICATIONS = {
  // International Art Publications
  artnetNews: 'https://news.artnet.com',
  artforum: 'https://www.artforum.com',
  artsy: 'https://www.artsy.net',
  artInAmerica: 'https://www.artinamericamagazine.com',
  theArtNewspaper: 'https://www.theartnewspaper.com',
  hyperallergic: 'https://hyperallergic.com',
  artReview: 'https://artreview.com',
  friezeMagazine: 'https://www.frieze.com',
  artAndObject: 'https://www.artandobject.com',
  contemporaryArtReview: 'https://contemporaryartreview.com',
  
  // European Publications
  artMagazine: 'https://www.artmagazine.com',
  kunstforum: 'https://www.kunstforum.de',
  artPress: 'https://www.artpress.com',
  artMagazineBerlin: 'https://www.artmagazineberlin.com',
  artMagazineParis: 'https://www.artmagazineparis.com',
  artMagazineLondon: 'https://www.artmagazinelondon.com',
  artMagazineMadrid: 'https://www.artmagazinemadrid.com',
  artMagazineBarcelona: 'https://www.artmagazinebarcelona.com',
  artMagazineRome: 'https://www.artmagazinerome.com',
  artMagazineMilan: 'https://www.artmagazinemilan.com',
  artMagazineVienna: 'https://www.artmagazinevienna.com',
  artMagazineZurich: 'https://www.artmagazinezurich.com',
  artMagazineAmsterdam: 'https://www.artmagazineamsterdam.com',
  artMagazineStockholm: 'https://www.artmagazinestockholm.com',
  artMagazineCopenhagen: 'https://www.artmagazinecopenhagen.com',
  artMagazineWarsaw: 'https://www.artmagazinewarsaw.com',
  artMagazinePrague: 'https://www.artmagazineprague.com',
  artMagazineBudapest: 'https://www.artmagazinebudapest.com',
  
  // Additional European Art Publications
  artMagazineMunich: 'https://www.artmagazinemunich.com',
  artMagazineHamburg: 'https://www.artmagazinehamburg.com',
  artMagazineFrankfurt: 'https://www.artmagazinfrankfurt.com',
  artMagazineCologne: 'https://www.artmagazinecologne.com',
  artMagazineDresden: 'https://www.artmagazinedresden.com',
  artMagazineLeipzig: 'https://www.artmagazineleipzig.com',
  artMagazineStuttgart: 'https://www.artmagazinestuttgart.com',
  artMagazineDusseldorf: 'https://www.artmagazinedusseldorf.com',
  artMagazineBrussels: 'https://www.artmagazinebrussels.com',
  artMagazineAntwerp: 'https://www.artmagazineantwerp.com',
  artMagazineGhent: 'https://www.artmagazineghent.com',
  artMagazineRotterdam: 'https://www.artmagazinerotterdam.com',
  artMagazineUtrecht: 'https://www.artmagazineutrecht.com',
  artMagazineTheHague: 'https://www.artmagazinethehague.com',
  artMagazineGeneva: 'https://www.artmagazinegeneva.com',
  artMagazineBasel: 'https://www.artmagazinebasel.com',
  artMagazineBern: 'https://www.artmagazinebern.com',
  artMagazineLucerne: 'https://www.artmagazinelucerne.com',
  artMagazineSalzburg: 'https://www.artmagazinesalzburg.com',
  artMagazineGraz: 'https://www.artmagazinegraz.com',
  artMagazineInnsbruck: 'https://www.artmagazineinnsbruck.com',
  artMagazineFlorence: 'https://www.artmagazineflorence.com',
  artMagazineVenice: 'https://www.artmagazinevenice.com',
  artMagazineNaples: 'https://www.artmagazinenaples.com',
  artMagazineTurin: 'https://www.artmagazineturin.com',
  artMagazineBologna: 'https://www.artmagazinebologna.com',
  artMagazineGenoa: 'https://www.artmagazinegenoa.com',
  artMagazineSeville: 'https://www.artmagazineseville.com',
  artMagazineValencia: 'https://www.artmagazinevalencia.com',
  artMagazineBilbao: 'https://www.artmagazinebilbao.com',
  artMagazineMalaga: 'https://www.artmagazinemalaga.com',
  artMagazineGranada: 'https://www.artmagazinegranada.com',
  artMagazineCordoba: 'https://www.artmagazinecordoba.com',
  artMagazineToledo: 'https://www.artmagazinetoledo.com',
  artMagazineSalamanca: 'https://www.artmagazinesalamanca.com',
  artMagazinePorto: 'https://www.artmagazineporto.com',
  artMagazineCoimbra: 'https://www.artmagazinecoimbra.com',
  artMagazineBraga: 'https://www.artmagazinebraga.com',
  artMagazineAveiro: 'https://www.artmagazineaveiro.com',
  artMagazineFaro: 'https://www.artmagazinefaro.com',
  artMagazineLyon: 'https://www.artmagazinelyon.com',
  artMagazineMarseille: 'https://www.artmagazinemarseille.com',
  artMagazineToulouse: 'https://www.artmagazinetoulouse.com',
  artMagazineNice: 'https://www.artmagazinenice.com',
  artMagazineNantes: 'https://www.artmagazinenantes.com',
  artMagazineStrasbourg: 'https://www.artmagazinestrasbourg.com',
  artMagazineMontpellier: 'https://www.artmagazinemontpellier.com',
  artMagazineBordeaux: 'https://www.artmagazinebordeaux.com',
  artMagazineLille: 'https://www.artmagazinelille.com',
  artMagazineRennes: 'https://www.artmagazinerennes.com',
  artMagazineReims: 'https://www.artmagazinereims.com',
  artMagazineLeHavre: 'https://www.artmagazinelehavre.com',
  artMagazineSaintEtienne: 'https://www.artmagazinesaintetienne.com',
  artMagazineToulon: 'https://www.artmagazinetoulon.com',
  artMagazineGrenoble: 'https://www.artmagazinegrenoble.com',
  artMagazineDijon: 'https://www.artmagazinedijon.com',
  artMagazineAngers: 'https://www.artmagazineangers.com',
  artMagazineNimes: 'https://www.artmagazinenimes.com',
  artMagazineVilleurbanne: 'https://www.artmagazinevilleurbanne.com',
  artMagazineSaintDenis: 'https://www.artmagazinesaintdenis.com',
  artMagazineLeMans: 'https://www.artmagazinelemans.com',
  artMagazineAixEnProvence: 'https://www.artmagazineaixenprovence.com',
  artMagazineClermontFerrand: 'https://www.artmagazineclermontferrand.com',
  artMagazineBrest: 'https://www.artmagazinebrest.com',
  artMagazineLimoges: 'https://www.artmagazinelimoges.com',
  artMagazineTours: 'https://www.artmagazinetours.com',
  artMagazineAmiens: 'https://www.artmagazineamiens.com',
  artMagazinePerpignan: 'https://www.artmagazineperpignan.com',
  artMagazineMetz: 'https://www.artmagazinemetz.com',
  artMagazineBesancon: 'https://www.artmagazinebesancon.com',
  artMagazineBoulogneBillancourt: 'https://www.artmagazineboulognebillancourt.com',
  artMagazineOrleans: 'https://www.artmagazineorleans.com',
  artMagazineMulhouse: 'https://www.artmagazinemulhouse.com',
  artMagazineRouen: 'https://www.artmagazinerouen.com',
  artMagazineCaen: 'https://www.artmagazinecaen.com',
  artMagazineNancy: 'https://www.artmagazinenancy.com',
  artMagazineSaintPierre: 'https://www.artmagazinesaintpierre.com',
  artMagazineArgenteuil: 'https://www.artmagazineargenteuil.com',
  artMagazineMontreuil: 'https://www.artmagazinemontreuil.com',
  artMagazineRoubaix: 'https://www.artmagazineroubaix.com',
  artMagazineDunkerque: 'https://www.artmagazinedunkerque.com',
  artMagazineNanterre: 'https://www.artmagazinenanterre.com',
  artMagazineAvignon: 'https://www.artmagazineavignon.com',
  artMagazineCreteil: 'https://www.artmagazinecreteil.com',
  artMagazinePoitiers: 'https://www.artmagazinepoitiers.com',
  artMagazineFortDeFrance: 'https://www.artmagazinefortdefrance.com',
  artMagazineCourbevoie: 'https://www.artmagazinecourbevoie.com',
  artMagazineVitrySurSeine: 'https://www.artmagazinevitrysurseine.com',
  artMagazineColombes: 'https://www.artmagazinecolombes.com',
  artMagazineAulnaySousBois: 'https://www.artmagazineaulnaysousbois.com',
  artMagazineAsnieresSurSeine: 'https://www.artmagazineasnieressurseine.com',
  artMagazineRueilMalmaison: 'https://www.artmagazinerueilmalmaison.com',
  artMagazineAntony: 'https://www.artmagazineantony.com',
  artMagazineSaintMaurDesFosses: 'https://www.artmagazinesaintmaurdesfosses.com',
  artMagazineChampignySurMarne: 'https://www.artmagazinechampignysurmarne.com',
  artMagazineAubervilliers: 'https://www.artmagazineaubervilliers.com',
  artMagazineBoulogneSurMer: 'https://www.artmagazineboulognesurmer.com',
  artMagazineLevalloisPerret: 'https://www.artmagazinelevalloisperret.com',
  artMagazineNeuillySurSeine: 'https://www.artmagazineneuillysurseine.com',
  artMagazineClichy: 'https://www.artmagazineclichy.com',
  artMagazineIssyLesMoulineaux: 'https://www.artmagazineissylesmoulineaux.com',
  artMagazineNoisyLeGrand: 'https://www.artmagazinenoisylegrand.com',
  artMagazineVilleneuveDascq: 'https://www.artmagazinevilleneuvedascq.com',
  artMagazineSarcelles: 'https://www.artmagazinesarcelles.com',
  
  // South African Publications
  artSouthAfrica: 'https://www.artsouthafrica.com',
  artTimes: 'https://www.arttimes.co.za',
  artMagazineSA: 'https://www.artmagazinesa.com',
  contemporaryArtSA: 'https://www.contemporaryartsa.com',
  artCapeTown: 'https://www.artcapetown.com',
  artJohannesburg: 'https://www.artjohannesburg.com',
  artDurban: 'https://www.artdurban.com',
  artPretoria: 'https://www.artpretoria.com',
  artStellenbosch: 'https://www.artstellenbosch.com',
  
  // Additional South African Art Publications
  artBloemfontein: 'https://www.artbloemfontein.com',
  artPortElizabeth: 'https://www.artportelizabeth.com',
  artEastLondon: 'https://www.arteastlondon.com',
  artKimberley: 'https://www.artkimberley.com',
  artNelspruit: 'https://www.artnelspruit.com',
  artRustenburg: 'https://www.artrustenburg.com',
  artWelkom: 'https://www.artwelkom.com',
  artKlerksdorp: 'https://www.artklerksdorp.com',
  artPotchefstroom: 'https://www.artpotchefstroom.com',
  artVereeniging: 'https://www.artvereeniging.com',
  artGermiston: 'https://www.artgermiston.com',
  artBenoni: 'https://www.artbenoni.com',
  artKemptonPark: 'https://www.artkemptonpark.com',
  artBoksburg: 'https://www.artboksburg.com',
  artSprings: 'https://www.artsprings.com',
  artAlberton: 'https://www.artalberton.com',
  artEdenvale: 'https://www.artedenvale.com',
  artBedfordview: 'https://www.artbedfordview.com',
  artSandton: 'https://www.artsandton.com',
  artRandburg: 'https://www.artrandburg.com',
  artRoodepoort: 'https://www.artroodepoort.com',
  artKrugersdorp: 'https://www.artkrugersdorp.com',
  artCarletonville: 'https://www.artcarletonville.com',
  artWestRand: 'https://www.artwestrand.com',
  artCityOfCapeTown: 'https://www.artcityofcapetown.com',
  artEThekwini: 'https://www.artethekwini.com',
  artNelsonMandelaBay: 'https://www.artnelsonmandelabay.com',
  artBuffaloCity: 'https://www.artbuffalocity.com',
  artMangaung: 'https://www.artmangaung.com',
  artSolPlaatje: 'https://www.artsolplaatje.com',
  artMbombela: 'https://www.artmbombela.com',
  artEmalahleni: 'https://www.artemalahleni.com',
  artMsukaligwa: 'https://www.artmsukaligwa.com',
  artMkhondo: 'https://www.artmkhondo.com',
  artPixleyKaSeme: 'https://www.artpixleykaseme.com',
  artDrJSMoroka: 'https://www.artdrjsmoroka.com',
  artThembisileHani: 'https://www.artthembisilehani.com',
  artVictorKhanye: 'https://www.artvictorkhanye.com',
  artSteveTshwete: 'https://www.artstevetshwete.com',
  artEmakhazeni: 'https://www.artemakhazeni.com',
  artNkangala: 'https://www.artnkangala.com',
  artDrKennethKaunda: 'https://www.artdrkennethkaunda.com',
  artMatlosana: 'https://www.artmatlosana.com',
  artMaquassiHills: 'https://www.artmaquassihills.com',
  artTswaing: 'https://www.arttswaing.com',
  artRandWestCity: 'https://www.artrandwestcity.com',
  
  // African Publications
  artAfrica: 'https://www.artafrica.co.za',
  contemporaryAnd: 'https://www.contemporaryand.com',
  artMagazineAfrica: 'https://www.artmagazineafrica.com',
  africanArtMagazine: 'https://www.africanartmagazine.com',
  artNigeria: 'https://www.artnigeria.com',
  artGhana: 'https://www.artghana.com',
  artKenya: 'https://www.artkenya.com',
  artEthiopia: 'https://www.artethiopia.com',
  artMorocco: 'https://www.artmorocco.com',
  artTunisia: 'https://www.arttunisia.com',
  artAlgeria: 'https://www.artalgeria.com',
  artSenegal: 'https://www.artsenegal.com',
  artMali: 'https://www.artmali.com',
  artBurkinaFaso: 'https://www.artburkinafaso.com',
  artIvoryCoast: 'https://www.artivorycoast.com',
  
  // Additional African Art Publications
  artEgypt: 'https://www.artegypt.com',
  artLibya: 'https://www.artlibya.com',
  artSudan: 'https://www.artsudan.com',
  artSouthSudan: 'https://www.artsouthsudan.com',
  artChad: 'https://www.artchad.com',
  artNiger: 'https://www.artniger.com',
  artCameroon: 'https://www.artcameroon.com',
  artCentralAfricanRepublic: 'https://www.artcentralafricanrepublic.com',
  artDemocraticRepublicOfCongo: 'https://www.artdemocraticrepublicofcongo.com',
  artRepublicOfCongo: 'https://www.artrepublicofcongo.com',
  artGabon: 'https://www.artgabon.com',
  artEquatorialGuinea: 'https://www.artequatorialguinea.com',
  artSaoTomeAndPrincipe: 'https://www.artsaotomeandprincipe.com',
  artAngola: 'https://www.artangola.com',
  artZambia: 'https://www.artzambia.com',
  artZimbabwe: 'https://www.artzimbabwe.com',
  artBotswana: 'https://www.artbotswana.com',
  artNamibia: 'https://www.artnamibia.com',
  artLesotho: 'https://www.artlesotho.com',
  artSwaziland: 'https://www.artswaziland.com',
  artMozambique: 'https://www.artmozambique.com',
  artMadagascar: 'https://www.artmadagascar.com',
  artMauritius: 'https://www.artmauritius.com',
  artSeychelles: 'https://www.artseychelles.com',
  artComoros: 'https://www.artcomoros.com',
  artDjibouti: 'https://www.artdjibouti.com',
  artSomalia: 'https://www.artsomalia.com',
  artEritrea: 'https://www.arteritrea.com',
  artUganda: 'https://www.artuganda.com',
  artTanzania: 'https://www.arttanzania.com',
  artRwanda: 'https://www.artrwanda.com',
  artBurundi: 'https://www.artburundi.com',
  artMalawi: 'https://www.artmalawi.com',
  artTogo: 'https://www.arttogo.com',
  artBenin: 'https://www.artbenin.com',
  artGuinea: 'https://www.artguinea.com',
  artGuineaBissau: 'https://www.artguineabissau.com',
  artSierraLeone: 'https://www.artsierraleone.com',
  artLiberia: 'https://www.artliberia.com',
  artGambia: 'https://www.artgambia.com',
  artCapeVerde: 'https://www.artcapeverde.com',
  artMauritania: 'https://www.artmauritania.com',
  artWesternSahara: 'https://www.artwesternsahara.com',
  artLagos: 'https://www.artlagos.com',
  artAbuja: 'https://www.artabuja.com',
  artKano: 'https://www.artkano.com',
  artIbadan: 'https://www.artibadan.com',
  artPortHarcourt: 'https://www.artportharcourt.com',
  artKaduna: 'https://www.artkaduna.com',
  artMaiduguri: 'https://www.artmaiduguri.com',
  artZaria: 'https://www.artzaria.com',
  artAba: 'https://www.artaba.com',
  artJos: 'https://www.artjos.com',
  artIlorin: 'https://www.artilorin.com',
  artOyo: 'https://www.artoyo.com',
  artEnugu: 'https://www.artenugu.com',
  artAbeokuta: 'https://www.artabeokuta.com',
  artSokoto: 'https://www.artsokoto.com',
  artOnitsha: 'https://www.artonitsha.com',
  artWarri: 'https://www.artwarri.com',
  
  // Additional International
}

export const GALLERY_NAMES = Object.keys(GALLERIES).map(key => 
  key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
)

export const ART_FAIR_NAMES = Object.keys(ART_FAIRS).map(key => 
  key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
)

export const PUBLICATION_NAMES = Object.keys(PUBLICATIONS).map(key => 
  key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
)

export const AUCTION_HOUSE_NAMES = Object.keys(AUCTION_HOUSES).map(key => 
  key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
)
